name: Unzip File

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Unzip file
      run: |
        sudo apt-get install unzip
        unzip speech-ai-music\ \(1\).zip -d extracted_files/
